### ISSUE TITLE
Windows 11 normal user problem

### ISSUE THREAD

**Issue by vampiebar** [LiuBaihao-Hello/Sudo-for-Windos#1]
Windows 11 "normal user" / "standard user" has been tested?
I could not make it run with Windows 11 normal user.. 
Super user in Server 2019 and Windows 11 ( default user tested ) successfully.

What can be blocking normal user with Windows 11 to reach the SudoService.exe ?

**Comment by MythicAstra** [comment]
If run the program as a standard user, the service (`SudoService.exe`) cannot get the elevated token of the user, which is a limitation of Windows.

To run elevated processes, the user should be an administrator.
How can a standard user run elevated processes? Of course, it is not possible.

If you mean that you want to run programs as another administrator account in a standard user environment, the tool currently does not implement this feature.
I'm not working on this project now, maybe I will add the feature in the future.
